connect('weblogic','that is a secret','t3://cernanappiloadbalancer:7001/em')
edit()
startEdit()
create('anappilb','Machine')
cd('Machines/anappilb/NodeManager/anappilb')
set('ListenAddress','cernanappiloadbalancer')
set('ListenPort','5556')
set('NMType','Plain')
save()
stopEdit('y')
exit('y')
